spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: Citronix
    password: Citronix
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: db/changelog/master.yaml
server:
  port: 8081